export const defaultMenus = [
    {
        name: "Dashboard",
        parentId: null,
        groupLabel: "Main",
        icon: "LayoutDashboard",
        url: "/dashboard",
        sortOrder: 1,
        isActive: true,
        isAction: false,
    },
    {
        name: "Tenant",
        parentId: null,
        groupLabel: "Business Management",
        icon: "Building",
        url: "/tenant",
        sortOrder: 2,
        isActive: true,
        isAction: false,
    },
    {
        name: "Role",
        parentId: null,
        groupLabel: "Business Management",
        icon: "UserCog",
        url: "/roles",
        sortOrder: 3,
        isActive: true,
        isAction: false,
    },
    {
        name: "Role Access",
        parentId: null,
        groupLabel: "Business Management",
        icon: "UserCog",
        url: "/role-access",
        sortOrder: 4,
        isActive: true,
        isAction: false,
    },
    {
        name: "User Access",
        parentId: null,
        groupLabel: "Business Management",
        icon: "UserCheck",
        url: "/user-access",
        sortOrder: 5,
        isActive: true,
        isAction: false,
    },
];